### ISSUE TITLE
ValueError: unknown url type

### ISSUE THREAD

**Issue by TiredSounds** [ids1024/wikicurses#3]
I run into an error like the following when trying to access something other than wikipedia:

```
Traceback (most recent call last):
  File "/usr/bin/wikicurses", line 9, in <module>
    load_entry_point('Wikicurses==1.3', 'console_scripts', 'wikicurses')()
  File "/usr/lib/python3.5/site-packages/wikicurses/main.py", line 583, in main
    loop.run()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 715, in _loop
    alarm_callback()
  File "/usr/lib/python3.5/site-packages/urwid/main_loop.py", line 164, in cb
    callback(self, user_data)
  File "/usr/lib/python3.5/site-packages/wikicurses/main.py", line 580, in <lambda>
    callback = lambda x, y: openPage(args.feed or args.search, bool(args.feed))
  File "/usr/lib/python3.5/site-packages/wikicurses/main.py", line 423, in openPage
    page = wiki.search(title)
  File "/usr/lib/python3.5/site-packages/wikicurses/wiki.py", line 162, in search
    format="json", redirects=True
  File "/usr/lib/python3.5/site-packages/wikicurses/wiki.py", line 96, in _query
    return urllib.request.urlopen(url, data).read().decode('utf-8')
  File "/usr/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 450, in open
    req = Request(fullurl, data)
  File "/usr/lib/python3.5/urllib/request.py", line 268, in __init__
    self.full_url = url
  File "/usr/lib/python3.5/urllib/request.py", line 294, in full_url
    self._parse()
  File "/usr/lib/python3.5/urllib/request.py", line 323, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: 'ArchWiki?format=json&action=parse&page=Dwm&prop=externallinks%7Ciwlinks%7Clanglinks%7Clinks%7Cdisplaytitle%7Cproperties%7Ctext&redirects=True'
```

The above was specifically with the `wikicurses -w ArchWiki Dwm` example from the manpage.

(The package is wikicurses-git from the AUR, I also tried the non-git version with no luck).

**Comment by ids1024** [comment]
Oh, the problem is that the archwiki is not configured. Add this to `~/.config/wikicurses/config` (or `/etc/wikicurses.conf`):

``` ini
[ArchWiki]
url = https://wiki.archlinux.org/api.php
```

Perhaps that should be in the default configuration...

Edit: And the exception should be caught, and a useful error message produced...

**Comment by TiredSounds** [comment]
Ah cheers. I didn't catch that there was a manpage for the config too.

Closing
