### ISSUE TITLE
DistributionNotFound: The 'urwid' distribution was not found and is required by Wikicurses

### ISSUE THREAD

**Issue by vitomanue** [ids1024/wikicurses#7]
Hello. Yesterday I migrated from Manjaro to Antergos. After install wikicurses, I receive this error every time I try to run the program:

“Traceback (most recent call last):
  File "/usr/bin/wikicurses", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'urwid' distribution was not found and is required by Wikicurses”

Any solution for this?

**Comment by ids1024** [comment]
How are you installing wikicurses? You might want to try installing from the AUR package: https://aur.archlinux.org/packages/wikicurses/

Otherwise, install the `python-urwid` package with Pacman.

**Comment by vitomanue** [comment]
A simple `yaourt -Syu --aur` solved the problem.
Sorry for take your time. I‘m new to linux and get lost pretty easily.

By the way, I really like your program. Thank you.
