### ISSUE TITLE
list index out of range error on german wikipedia api

### ISSUE THREAD

**Issue by rabuzarus** [ids1024/wikicurses#8]
If I change the url in the wikicurses config to `url = https://de.wikipedia.org/w/api.php` I got `IndexError: list index out of range`
```
Traceback (most recent call last):
  File "/home/pi/.local/bin/wikicurses", line 11, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.5/site-packages/wikicurses/main.py", line 584, in main
    loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 682, in run
    self._loop()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 715, in _loop
    alarm_callback()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 164, in cb
    callback(self, user_data)
  File "/home/pi/.local/lib/python3.5/site-packages/wikicurses/main.py", line 581, in <lambda>
    callback = lambda x, y: openPage(args.feed or args.search, bool(args.feed))
  File "/home/pi/.local/lib/python3.5/site-packages/wikicurses/main.py", line 434, in openPage
    mainwidget.body = Pager(page)
  File "/home/pi/.local/lib/python3.5/site-packages/wikicurses/main.py", line 337, in __init__
    self._render()
  File "/home/pi/.local/lib/python3.5/site-packages/wikicurses/main.py", line 355, in _render
    widget = urwid.Text(curtext, align=prevalign)
  File "/usr/lib/python3/dist-packages/urwid/widget.py", line 836, in __init__
    self.set_text(markup)
  File "/usr/lib/python3/dist-packages/urwid/widget.py", line 879, in set_text
    self._text, self._attrib = decompose_tagmarkup(markup)
  File "/usr/lib/python3/dist-packages/urwid/util.py", line 377, in decompose_tagmarkup
    text = tl[0][:0].join(tl)
IndexError: list index out of range
```

Python 3.5.3

**Comment by ids1024** [comment]
I'm not sure what's causing this. But since the exception is coming from [urwid](https://github.com/urwid/urwid), I'm guessing it's probably a bug there?

Edit: Or maybe not. It looks like `curtext` is `[]`, which is probably incorrect...
